### ISSUE TITLE
setup.py installs Python scripts as 'data' rather than 'scripts'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/python-gflags#12]
```
The setup.py script lists the Python script as a 'data file', alike:

      data_files=[("bin", ["gflags2man.py"])],

while it should be a 'script' instead:

      scripts=["gflags2man.py"],

Installing it a script will make sure that distutils correctly update the 
Python shebang and make the script executable.

I'm attaching a patch fixing setup.py.
```

Original issue reported on code.google.com by `mgo...@gentoo.org` on 16 Dec 2012 at 3:41

Attachments:
- [python-gflags-2.0-scripts-install.patch](https://storage.googleapis.com/google-code-attachments/python-gflags/issue-12/comment-0/python-gflags-2.0-scripts-install.patch)

**Comment by gpshead** [comment]
python-gflags users should migrate to absl-py:
 https://github.com/abseil/abseil-py
 https://pypi.python.org/pypi/absl-py/

It is the modern version of this library.
