### ISSUE TITLE
gflags_unittest.py does not respect TMPDIR

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/python-gflags#13]
```
The tests in gflags_unittest.py rely on a hardcoded path in /tmp. This raises 
sandbox violations when the build is performed in an isolated environment, and 
has a collision potential when running tests for multiple Python 
implementations in parallel.

The test should at least respect the TMPDIR environment variable. I'm attaching 
a patch which uses tempfile.mkdtemp() to obtain an unique temporary directory, 
respecting TMPDIR.
```

Original issue reported on code.google.com by `mgo...@gentoo.org` on 16 Dec 2012 at 4:06

Attachments:
- [python-gflags-2.0-tests-respect-tmpdir.patch](https://storage.googleapis.com/google-code-attachments/python-gflags/issue-13/comment-0/python-gflags-2.0-tests-respect-tmpdir.patch)

**Comment by gpshead** [comment]
python-gflags users should migrate to absl-py:
 https://github.com/abseil/abseil-py
 https://pypi.python.org/pypi/absl-py/

It is the modern version of this library.
