### ISSUE TITLE
Test for permission errors fails as root

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/python-gflags#14]
```
When running unit tests as root (i.e. as part of a install process that runs as 
root) one test fails because root can still read files with 0 for permissions. 
Attached is a pretty trivial way to skip the test that is compatible with any 
version of python. A fancier way in >= 2.7 would be to call self.skipTest().
```

Original issue reported on code.google.com by `marin...@gmail.com` on 28 Jun 2013 at 6:37

Attachments:
- [python-gflags-2.0-skip-permission-test-as-root.patch](https://storage.googleapis.com/google-code-attachments/python-gflags/issue-14/comment-0/python-gflags-2.0-skip-permission-test-as-root.patch)

**Comment by gpshead** [comment]
python-gflags users should migrate to absl-py:
 https://github.com/abseil/abseil-py
 https://pypi.python.org/pypi/absl-py/

It is the modern version of this library.
