### ISSUE TITLE
ImportError: No module named third_party.pep257

### ISSUE THREAD

**Issue by slafs** [google/python-gflags#25]
See: https://github.com/google/python-gflags/commit/e0744961a37ae121241d4eb2ea0b5f2135f121fd#commitcomment-17068110

After upgrading to 3.0.3 `closure-linter` fails with:
```
...
 import gflags.third_party.pep257 as pep257
ImportError: No module named third_party.pep257
```

**Comment by thiagomoretto** [comment]
Same problem here. OR-tools is broken too. Is there a workaround or something else we can do?
