### ISSUE TITLE
Please clarify github.com/gflags/python-gflags

### ISSUE THREAD

**Issue by noahl** [google/python-gflags#27]
I found what looks like an out-of-date version of this repository at github.com/gflags/python-gflags. That repository is linked to by https://code.google.com/archive/p/python-gflags/, so I thought it was the official repository for quite a while. If that repository is owned by the same people as this one, please consider either removing it from github (ideally) or adding a note to the README file there that this repository is kept up-to-date.

If possible, it would also be great to update https://code.google.com/archive/p/python-gflags/, but less important.

**Comment by cclauss** [comment]
@noahl Can you please click "Close" on this issue?

**Comment by noahl** [comment]
Yes, I see the fix. Thank you!
