### ISSUE TITLE
Documentation and examples

### ISSUE THREAD

**Issue by tedivm** [google/python-gflags#30]
It would be nice if this project published documentation and examples. 

As a secondary issue the readme refers to a "gflags.py" file which does not exist. Presumably this should just be "flags.py".

**Comment by frmsaul** [comment]
+1

You guys should really publish some examples.

**Comment by korman** [comment]
Good

**Comment by gpshead** [comment]
A trivial example can be see in https://github.com/abseil/abseil-py/blob/master/smoke_tests/smoke_test.py

We haven't published the full documentation yet (it is coming and will be on abseil.io), but this python-gflags project is obsoleted by https://github.com/abseil/abseil-py (absl-py on PyPI) which is a modern version of the same code that we are actually setup to _maintain_ on Github.
