### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by jakirkham** [google/python-gflags#35]
It looks like there was a switch to `distutils` from `setuptools`. Though there is an attempt to manage dependencies with it (i.e. `six`), but that won't work. Only `setuptools` supports that behavior. Also would the keyword needs to be changed.

xref: https://github.com/google/python-gflags/commit/21f866832a20c6c7cc53930a39953afab0e8eda2#commitcomment-21106396

**Comment by gpshead** [comment]
python-gflags users should migrate to absl-py:
 https://github.com/abseil/abseil-py
 https://pypi.python.org/pypi/absl-py/

It is the modern version of this library.
