### ISSUE TITLE
ERROR:root:Trying to access flag xxx before flags were parsed.

### ISSUE THREAD

**Issue by LucasMahieu** [google/python-gflags#37]
I am facing an issue when I want to use python gflags.
Here is how I am using it :  

```
import gflags
FLAGS = gflags.FLAGS
gflags.DEFINE_integer('xxx', 3,'xxx')
if FLAGS.xxx == 3:
    print ok
```

I run the program with : `python myProg.py`

It seems that the program is working, but I always have this error message : 

> ERROR:root:Trying to access flag xxx before flags were parsed.
> Traceback (most recent call last):
>   File "/home/toto/PythonEnv/local/lib/python2.7/site-packages/gflags/flagvalues.py", line 535, in __getattr__
>     raise exceptions.UnparsedFlagAccessError(error_message)
> UnparsedFlagAccessError: Trying to access flag xxx before flags were parsed.

Do you know why ?

**Comment by vrusinov** [comment]
Yes, you need to explicitly to tell flags library to parse argv before you can access FLAGS.xxx. Something like `FLAGS(sys.argv)`.

if you are using google.apputil, app.run() should do that for you.

**Comment by LucasMahieu** [comment]
thanks a lot, its solves the issue
