### ISSUE TITLE
Error running "acoustics_1d_example1.ipynb"

### ISSUE THREAD

**Issue by ceresmom** [google/python-gflags#42]
I tried running the acoustics 1D example using the Jupyter notebook but I had an error:

> IndexError: list index out of range. 

Can someone please help me solve this code error?I'm a beginner in clawpack and python language. Below is the code that gives the error and the error message received.

`import clawpack.visclaw.JSAnimation.JSAnimation_frametools as J
anim = J.make_anim(plotdir, figno=1, figsize=(6,4))
anim`

IndexError                                Traceback (most recent call last)
<ipython-input-9-311667457c9f> in <module>()
      1 import clawpack.visclaw.JSAnimation.JSAnimation_frametools as J
----> 2 anim = J.make_anim(plotdir, figno=1, figsize=(6,4))
      3 anim

~/anaconda3/lib/python3.6/site-packages/clawpack/visclaw/JSAnimation/JSAnimation_frametools.py in make_anim(plotdir, fname_base, figno, figsize)
     80     ax = fig.add_axes([0, 0, 1, 1])
     81     ax.axis('off')  # so there's not a second set of axes
---> 82     im = plt.imshow(image.imread(filenames[0]))
     83 
     84     def init():

IndexError: list index out of range

**Comment by yilei** [comment]
Looks like a wrong GitHub repo. I believe you want to report here instead: https://github.com/clawpack/pyclaw/issues?
